import type {Metadata} from 'next';
import './globals.css';
import Provider from "@/components/Provider";

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
																		 children,
																	 }: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
		<body className="flex justify-center">
		<Provider>
			{children}
		</Provider>
		</body>
		</html>
	);
}
